import type {
  Contact,
  ScheduleItem,
  TravelDocument,
  Trip,
  TripUpdate,
} from './types';

export const mockTrips: Trip[] = [
  {
    id: 'trip-lisbon-2026',
    tripId: 'trip-lisbon-2026',
    title: 'Lisbon Client Onsite',
    destination: 'Lisbon, Portugal',
    description: '3-day onsite with Acme EU team. Flights, hotel and transfers are booked.',
    startDate: '2026-10-06',
    endDate: '2026-10-09',
    status: 'upcoming',
    travelerName: 'Alex Traveler',
    confirmationCode: 'TRV-8K2LQN',
  },
  {
    id: 'trip-tokyo-2026',
    tripId: 'trip-tokyo-2026',
    title: 'Tokyo Partner Summit',
    destination: 'Tokyo, Japan',
    description: 'Partner summit plus factory tour. Visa and JR Pass included.',
    startDate: '2026-11-12',
    endDate: '2026-11-17',
    status: 'upcoming',
    travelerName: 'Alex Traveler',
    confirmationCode: 'TRV-4T9PZD',
  },
];

export const mockSchedule: ScheduleItem[] = [
  {
    id: 'lis-day1-flight',
    tripId: 'trip-lisbon-2026',
    day: 'Day 1',
    date: '2026-10-06',
    startTime: '08:15',
    endTime: '10:30',
    title: 'Flight LH 1168 → LIS',
    description: 'Lufthansa, Seat 14A. Terminal 1, arrive 2h early.',
    location: 'FRA → LIS',
    kind: 'flight',
    status: 'confirmed',
  },
  {
    id: 'lis-day1-transfer',
    tripId: 'trip-lisbon-2026',
    day: 'Day 1',
    date: '2026-10-06',
    startTime: '11:00',
    endTime: '11:30',
    title: 'Airport transfer to hotel',
    description: 'Driver holding “TravelOps” sign at arrivals.',
    location: 'Lisbon Airport',
    kind: 'transfer',
    status: 'scheduled',
  },
  {
    id: 'lis-day1-checkin',
    tripId: 'trip-lisbon-2026',
    day: 'Day 1',
    date: '2026-10-06',
    startTime: '14:00',
    endTime: '15:00',
    title: 'Check in — Hotel Avenida Palace',
    description: 'Confirmation HAP-99213. Breakfast included.',
    location: 'Rua 1º de Dezembro 123',
    kind: 'hotel',
    status: 'confirmed',
  },
  {
    id: 'lis-day2-onsite',
    tripId: 'trip-lisbon-2026',
    day: 'Day 2',
    date: '2026-10-07',
    startTime: '09:30',
    endTime: '17:00',
    title: 'Acme EU onsite workshop',
    description: 'Bring passport for building access.',
    location: 'Acme Lisbon Office',
    kind: 'meeting',
    status: 'scheduled',
  },
  {
    id: 'lis-day3-return',
    tripId: 'trip-lisbon-2026',
    day: 'Day 3',
    date: '2026-10-08',
    startTime: '18:20',
    endTime: '22:35',
    title: 'Return flight LH 1169',
    description: 'Seat 15C. Check in opens 24h before.',
    location: 'LIS → FRA',
    kind: 'flight',
    status: 'scheduled',
  },
  {
    id: 'tok-day1-flight',
    tripId: 'trip-tokyo-2026',
    day: 'Day 1',
    date: '2026-11-12',
    startTime: '13:40',
    endTime: '09:25',
    title: 'Flight NH 210 → HND',
    description: 'ANA, Seat 22K. 12h 45m nonstop.',
    location: 'FRA → HND',
    kind: 'flight',
    status: 'confirmed',
  },
  {
    id: 'tok-day2-summit',
    tripId: 'trip-tokyo-2026',
    day: 'Day 2',
    date: '2026-11-13',
    startTime: '10:00',
    endTime: '16:00',
    title: 'Partner Summit Day 1',
    description: 'Keynote + breakout sessions.',
    location: 'Shibuya Conference Center',
    kind: 'meeting',
    status: 'scheduled',
  },
  {
    id: 'tok-day3-tour',
    tripId: 'trip-tokyo-2026',
    day: 'Day 3',
    date: '2026-11-14',
    startTime: '09:00',
    endTime: '13:00',
    title: 'Factory tour + lunch',
    description: 'Safety shoes provided onsite.',
    location: 'Yokohama Plant',
    kind: 'activity',
    status: 'scheduled',
  },
];

export const mockDocuments: TravelDocument[] = [
  {
    id: 'doc-passport',
    tripId: 'trip-lisbon-2026',
    title: 'Passport — Alex Traveler',
    kind: 'passport',
    reference: 'P •••• 4821',
    issuedTo: 'Alex Traveler',
    validUntil: '2031-04-01',
    offlineAvailable: true,
    notes: 'Keep a photo saved offline.',
  },
  {
    id: 'doc-lis-ticket',
    tripId: 'trip-lisbon-2026',
    title: 'E-ticket FRA ⇄ LIS',
    kind: 'ticket',
    reference: 'LH-1168-482199',
    issuedTo: 'Alex Traveler',
    offlineAvailable: true,
    notes: 'Check in via airline app.',
  },
  {
    id: 'doc-lis-hotel',
    tripId: 'trip-lisbon-2026',
    title: 'Hotel voucher — Avenida Palace',
    kind: 'hotel',
    reference: 'HAP-99213',
    issuedTo: 'Alex Traveler',
    offlineAvailable: true,
  },
  {
    id: 'doc-tok-passport',
    tripId: 'trip-tokyo-2026',
    title: 'Passport — Alex Traveler',
    kind: 'passport',
    reference: 'P •••• 4821',
    issuedTo: 'Alex Traveler',
    validUntil: '2031-04-01',
    offlineAvailable: true,
  },
  {
    id: 'doc-tok-visa',
    tripId: 'trip-tokyo-2026',
    title: 'Japan entry visa (90 days)',
    kind: 'visa',
    reference: 'V-JP-883120',
    issuedTo: 'Alex Traveler',
    validUntil: '2027-02-01',
    offlineAvailable: true,
  },
  {
    id: 'doc-tok-ticket',
    tripId: 'trip-tokyo-2026',
    title: 'E-ticket FRA ⇄ HND',
    kind: 'ticket',
    reference: 'NH-210-771200',
    issuedTo: 'Alex Traveler',
    offlineAvailable: true,
  },
];

export const mockContacts: Contact[] = [
  {
    id: 'c-emergency',
    tripId: 'trip-lisbon-2026',
    name: 'TravelOps 24/7 Support',
    role: 'Emergency hotline',
    phone: '+1-800-555-0199',
    email: 'sos@travelops.example',
    emergency: true,
  },
  {
    id: 'c-lis-manager',
    tripId: 'trip-lisbon-2026',
    name: 'Marta Silva',
    role: 'Trip coordinator',
    phone: '+351-21-555-0134',
    email: 'marta@travelops.example',
    emergency: false,
  },
  {
    id: 'c-lis-hotel',
    tripId: 'trip-lisbon-2026',
    name: 'Hotel Avenida Palace',
    role: 'Hotel front desk',
    phone: '+351-21-355-0200',
    emergency: false,
  },
  {
    id: 'c-tok-emergency',
    tripId: 'trip-tokyo-2026',
    name: 'TravelOps 24/7 Support',
    role: 'Emergency hotline',
    phone: '+1-800-555-0199',
    email: 'sos@travelops.example',
    emergency: true,
  },
  {
    id: 'c-tok-guide',
    tripId: 'trip-tokyo-2026',
    name: 'Ken Watanabe',
    role: 'Local guide',
    phone: '+81-90-5550-1122',
    emergency: false,
  },
];

export const mockUpdates: TripUpdate[] = [
  {
    id: 'u-lis-1',
    tripId: 'trip-lisbon-2026',
    title: 'Flight confirmed',
    message: 'LH 1168 is confirmed. Check-in opens 24h before departure.',
    createdAt: '2026-09-15T09:00:00Z',
    severity: 'info',
    read: false,
  },
  {
    id: 'u-lis-2',
    tripId: 'trip-lisbon-2026',
    title: 'Hotel upgraded',
    message: 'You were upgraded to a deluxe room with breakfast included.',
    createdAt: '2026-09-16T14:30:00Z',
    severity: 'info',
    read: false,
  },
  {
    id: 'u-tok-1',
    tripId: 'trip-tokyo-2026',
    title: 'Visa approved',
    message: 'Your Japan visa was approved. A copy is saved to Documents.',
    createdAt: '2026-09-14T08:00:00Z',
    severity: 'info',
    read: true,
  },
];
