import type {
  Contact,
  Hotel,
  Note,
  Participant,
  ScheduleItem,
  TransportLeg,
  TravelDocument,
  Trip,
  TripUpdate,
} from "./types";

const now = new Date().toISOString();

export const seedTrips: Trip[] = [
  {
    id: "trip-berlin",
    title: "Berlin AI Summit",
    destination: "Berlin, Germany",
    description:
      "Leadership + engineering delegation to the Berlin AI Summit. Keynotes, partner meetings, and a customer dinner.",
    startDate: "2026-10-06",
    endDate: "2026-10-10",
    status: "confirmed",
    budget: 48000,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "trip-tokyo",
    title: "Tokyo Client Tour",
    destination: "Tokyo & Osaka, Japan",
    description:
      "Enterprise client roadshow across Tokyo and Osaka with on-site workshops and exec briefings.",
    startDate: "2026-11-02",
    endDate: "2026-11-09",
    status: "planning",
    budget: 92000,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "trip-austin",
    title: "Austin Field Ops Review",
    destination: "Austin, USA",
    description:
      "Quarterly field operations review with support on-call rotation and vendor visits.",
    startDate: "2026-09-24",
    endDate: "2026-09-27",
    status: "in_progress",
    budget: 18000,
    createdAt: now,
    updatedAt: now,
  },
];

export const seedParticipants: Participant[] = [
  {
    id: "p-ber-1",
    tripId: "trip-berlin",
    name: "Amara Osei",
    email: "amara@travelops.ai",
    role: "Trip Lead",
    phone: "+49 170 000 111",
    passportNumber: "X4820113",
    status: "confirmed",
  },
  {
    id: "p-ber-2",
    tripId: "trip-berlin",
    name: "Jonas Weber",
    email: "jonas@travelops.ai",
    role: "Solutions Engineer",
    phone: "+49 170 000 222",
    passportNumber: "X9912004",
    status: "confirmed",
  },
  {
    id: "p-ber-3",
    tripId: "trip-berlin",
    name: "Priya Nair",
    email: "priya@travelops.ai",
    role: "Account Executive",
    phone: "+49 170 000 333",
    passportNumber: "X5527810",
    status: "pending",
  },
  {
    id: "p-tyo-1",
    tripId: "trip-tokyo",
    name: "Kenji Sato",
    email: "kenji@travelops.ai",
    role: "Regional Manager",
    phone: "+81 90 0000 1111",
    passportNumber: "J1029384",
    status: "confirmed",
  },
  {
    id: "p-tyo-2",
    tripId: "trip-tokyo",
    name: "Sofia Marino",
    email: "sofia@travelops.ai",
    role: "Customer Success",
    phone: "+81 90 0000 2222",
    passportNumber: "J5566778",
    status: "pending",
  },
  {
    id: "p-aus-1",
    tripId: "trip-austin",
    name: "Diego Ramos",
    email: "diego@travelops.ai",
    role: "Ops Manager",
    phone: "+1 512 000 1111",
    passportNumber: "U8830102",
    status: "confirmed",
  },
];

export const seedSchedules: ScheduleItem[] = [
  {
    id: "s-ber-1",
    tripId: "trip-berlin",
    title: "Arrival + hotel check-in",
    description: "Group arrival via BER, transfer to hotel.",
    location: "BER Airport → Hotel Adlon",
    startTime: "2026-10-06T14:00:00Z",
    endTime: "2026-10-06T16:00:00Z",
    kind: "transfer",
    status: "scheduled",
  },
  {
    id: "s-ber-2",
    tripId: "trip-berlin",
    title: "AI Summit Keynote",
    description: "Opening keynote, main stage.",
    location: "Messe Berlin, Hall A",
    startTime: "2026-10-07T09:00:00Z",
    endTime: "2026-10-07T11:00:00Z",
    kind: "meeting",
    status: "scheduled",
  },
  {
    id: "s-ber-3",
    tripId: "trip-berlin",
    title: "Customer dinner",
    description: "Dinner with Siemens Mobility stakeholders.",
    location: "Borchardt, Berlin",
    startTime: "2026-10-08T19:00:00Z",
    endTime: "2026-10-08T22:00:00Z",
    kind: "meal",
    status: "scheduled",
  },
  {
    id: "s-tyo-1",
    tripId: "trip-tokyo",
    title: "Exec briefing — FinTech client",
    description: "Discovery + demo at client HQ.",
    location: "Marunouchi, Tokyo",
    startTime: "2026-11-03T01:00:00Z",
    endTime: "2026-11-03T04:00:00Z",
    kind: "meeting",
    status: "scheduled",
  },
  {
    id: "s-tyo-2",
    tripId: "trip-tokyo",
    title: "Shinkansen to Osaka",
    description: "Team transfer, reserved seats.",
    location: "Tokyo → Shin-Osaka",
    startTime: "2026-11-06T02:00:00Z",
    endTime: "2026-11-06T05:00:00Z",
    kind: "transfer",
    status: "scheduled",
  },
  {
    id: "s-aus-1",
    tripId: "trip-austin",
    title: "Ops review day 1",
    description: "Q3 review with field teams.",
    location: "Austin HQ, Room 4B",
    startTime: "2026-09-24T14:00:00Z",
    endTime: "2026-09-24T21:00:00Z",
    kind: "meeting",
    status: "in_progress",
  },
];

export const seedHotels: Hotel[] = [
  {
    id: "h-ber-1",
    tripId: "trip-berlin",
    name: "Hotel Adlon Kempinski",
    address: "Unter den Linden 77, Berlin",
    checkIn: "2026-10-06",
    checkOut: "2026-10-10",
    confirmationCode: "ADL-88231",
    roomType: "Deluxe x3",
    status: "booked",
  },
  {
    id: "h-tyo-1",
    tripId: "trip-tokyo",
    name: "Park Hyatt Tokyo",
    address: "Shinjuku, Tokyo",
    checkIn: "2026-11-02",
    checkOut: "2026-11-06",
    confirmationCode: "PH-44021",
    roomType: "Twin x2",
    status: "booked",
  },
  {
    id: "h-tyo-2",
    tripId: "trip-tokyo",
    name: "St. Regis Osaka",
    address: "Chuo-ku, Osaka",
    checkIn: "2026-11-06",
    checkOut: "2026-11-09",
    confirmationCode: "SR-99120",
    roomType: "Deluxe x2",
    status: "pending",
  },
  {
    id: "h-aus-1",
    tripId: "trip-austin",
    name: "Fairmont Austin",
    address: "101 Red River St, Austin",
    checkIn: "2026-09-24",
    checkOut: "2026-09-27",
    confirmationCode: "FA-11087",
    roomType: "King x2",
    status: "checked_in",
  },
];

export const seedTransports: TransportLeg[] = [
  {
    id: "t-ber-1",
    tripId: "trip-berlin",
    mode: "flight",
    provider: "Lufthansa LH401",
    from: "JFK",
    to: "BER",
    departAt: "2026-10-06T02:30:00Z",
    arriveAt: "2026-10-06T12:00:00Z",
    referenceCode: "LH-XQ92A",
    status: "ticketed",
  },
  {
    id: "t-tyo-1",
    tripId: "trip-tokyo",
    mode: "flight",
    provider: "ANA NH109",
    from: "SFO",
    to: "HND",
    departAt: "2026-11-01T18:00:00Z",
    arriveAt: "2026-11-02T08:00:00Z",
    referenceCode: "ANA-QQ77Z",
    status: "ticketed",
  },
  {
    id: "t-tyo-2",
    tripId: "trip-tokyo",
    mode: "train",
    provider: "JR Shinkansen Nozomi",
    from: "Tokyo",
    to: "Shin-Osaka",
    departAt: "2026-11-06T02:00:00Z",
    arriveAt: "2026-11-06T05:00:00Z",
    referenceCode: "JR-OS228",
    status: "reserved",
  },
  {
    id: "t-aus-1",
    tripId: "trip-austin",
    mode: "flight",
    provider: "United UA2401",
    from: "DEN",
    to: "AUS",
    departAt: "2026-09-24T11:00:00Z",
    arriveAt: "2026-09-24T13:30:00Z",
    referenceCode: "UA-KL410",
    status: "completed",
  },
];

export const seedDocuments: TravelDocument[] = [
  {
    id: "d-ber-1",
    tripId: "trip-berlin",
    name: "Group flight e-tickets",
    type: "ticket",
    url: "https://files.example/berlin-etickets.pdf",
    issuedAt: "2026-08-20",
    expiresAt: "2026-10-10",
  },
  {
    id: "d-ber-2",
    tripId: "trip-berlin",
    name: "Travel insurance",
    type: "insurance",
    url: "https://files.example/berlin-insurance.pdf",
    issuedAt: "2026-08-22",
    expiresAt: "2026-10-11",
  },
  {
    id: "d-tyo-1",
    tripId: "trip-tokyo",
    name: "Japan visas",
    type: "visa",
    url: "https://files.example/tokyo-visas.pdf",
    issuedAt: "2026-09-01",
    expiresAt: "2027-03-01",
  },
];

export const seedContacts: Contact[] = [
  {
    id: "c-ber-1",
    tripId: "trip-berlin",
    name: "Lena Fischer",
    organization: "Messe Berlin",
    role: "Event Coordinator",
    email: "lena@messe-berlin.example",
    phone: "+49 30 000 111",
    notes: "Keynote logistics + badges",
  },
  {
    id: "c-ber-2",
    tripId: "trip-berlin",
    name: "Marco Held",
    organization: "Siemens Mobility",
    role: "VP Innovation",
    email: "marco.held@example.com",
    phone: "+49 170 555 010",
    notes: "Customer dinner host",
  },
  {
    id: "c-tyo-1",
    tripId: "trip-tokyo",
    name: "Yuki Tanaka",
    organization: "FinTech Client",
    role: "CTO",
    email: "yuki.t@example.com",
    phone: "+81 90 5555 0101",
    notes: "Exec briefing sponsor",
  },
  {
    id: "c-aus-1",
    tripId: "trip-austin",
    name: "Sarah Kim",
    organization: "Vendor — LoneStar Vans",
    role: "Dispatch",
    email: "sarah@lonestar.example",
    phone: "+1 512 555 0100",
    notes: "Ground transport",
  },
];

export const seedNotes: Note[] = [
  {
    id: "n-ber-1",
    tripId: "trip-berlin",
    author: "Amara Osei",
    title: "Badge pickup",
    body: "Badges can be collected Oct 6 after 15:00 at the north entrance.",
    createdAt: now,
  },
  {
    id: "n-tyo-1",
    tripId: "trip-tokyo",
    author: "Kenji Sato",
    title: "Pocket WiFi",
    body: "Order pocket WiFi for both travelers, deliver to Park Hyatt front desk.",
    createdAt: now,
  },
  {
    id: "n-aus-1",
    tripId: "trip-austin",
    author: "Diego Ramos",
    title: "Vendor ETA",
    body: "Vans arrive 30 min before each transfer. Confirm with Sarah day-of.",
    createdAt: now,
  },
];

export const seedUpdates: TripUpdate[] = [
  {
    id: "u-1",
    tripId: "trip-berlin",
    message: "LH401 to BER is on time. Group transfer confirmed.",
    severity: "info",
    createdAt: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
  },
  {
    id: "u-2",
    tripId: "trip-tokyo",
    message: "Osaka hotel still pending confirmation — following up with St. Regis.",
    severity: "warning",
    createdAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },
  {
    id: "u-3",
    tripId: "trip-austin",
    message: "Ops review day 1 started. 12 attendees checked in.",
    severity: "info",
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: "u-4",
    tripId: "trip-berlin",
    message: "Strike risk at BER Oct 7 — monitoring, backup transfer on standby.",
    severity: "critical",
    createdAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
  },
];
